### ISSUE TITLE
IntentEngine doesn't return the correct data when a "one_of" rule is matched

### ISSUE THREAD

**Issue by deevrek** [MycroftAI/adapt#65] opened 2017-08-28 17:58 UTC
Hello,
i noticed some issues in the Intent returned from intentEngine when a match with a "one_of" rule occurs:
1) It returns the "alias" instead of the "keyword"
2) _tags_ attribute includes the entire "match" instead of "entities" only
3) It only returns the first "keyword" matched

**Comment by clusterfudge** [comment] 2021-09-09 21:11
Hi @deevrek, sorry for the (extremely) delayed response here. There have been a number of fixes in the latest releases, including addressing some bugs in `one_of`. Please pull the latest and see if you can reproduce your issue. If so, I'm happy to take a look.

I'm marking this as `Close on 9/17` as part of triage for RT1. As the issue is 4+ years old, I'm not expecting a response. Apologies again, and thanks for contributing!

**Closed** 2021-09-17 21:50 UTC
Labels: Adapt: Road to 1.0.0, Close on 9/17
